### ISSUE TITLE
Firefox not working?

### ISSUE THREAD

**Issue by treyturner** [WillLuce/WebdriverIO_Typescript#2]
I can't seem to switch to firefox in wdio.conf.js and have things work correctly. When I try, Firefox opens, but nothing else happens (nothing is put into the address bar), and eventually the following is dumped to console:

```
> webdriver_typescript@1.0.0 test /home/tturner/dev/WebdriverIO_Typescript
> node ./node_modules/typescript/lib/tsc.js && node ./node_modules/webdriverio/bin/wdio && node ./node_modules/rimraf/bin.js src

[14:26:50]  COMMAND	POST 	 "/wd/hub/session"
[14:26:50]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"firefox","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.9.8","name":"webdriverio"}}}
ERROR: Unable to connect to host localhost on port 7055 after 45000 ms. Firefox console output:
illa.org to /usr/lib/firefox/browser/features/clicktoplay-rollout@mozilla.org.xpi
1510691213767	addons.xpi	INFO	Mapping activity-stream@mozilla.org to /usr/lib/firefox/browser/features/activity-stream@mozilla.org.xpi
1510691213767	addons.xpi	INFO	Mapping firefox@getpocket.com to /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1510691213767	addons.xpi	INFO	Mapping screenshots@mozilla.org to /usr/lib/firefox/browser/features/screenshots@mozilla.org.xpi
1510691213767	addons.xpi	INFO	Mapping followonsearch@mozilla.com to /usr/lib/firefox/browser/features/followonsearch@mozilla.com.xpi
1510691213767	addons.xpi	INFO	Mapping formautofill@mozilla.org to /usr/lib/firefox/browser/features/formautofill@mozilla.org.xpi
1510691213768	addons.xpi	INFO	Mapping shield-recipe-client@mozilla.org to /usr/lib/firefox/browser/features/shield-recipe-client@mozilla.org.xpi
1510691213768	addons.xpi	INFO	Mapping aushelper@mozilla.org to /usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi
1510691213768	addons.xpi	INFO	Mapping webcompat@mozilla.org to /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1510691213768	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi
1510691213768	addons.xpi	INFO	Mapping onboarding@mozilla.org to /usr/lib/firefox/browser/features/onboarding@mozilla.org.xpi
1510691213768	addons.xpi	DEBUG	Existing add-on clicktoplay-rollout@mozilla.org in app-system-defaults
1510691213768	addons.xpi	DEBUG	Existing add-on activity-stream@mozilla.org in app-system-defaults
1510691213768	addons.xpi	DEBUG	Existing add-on firefox@getpocket.com in app-system-defaults
1510691213769	addons.xpi	DEBUG	Existing add-on screenshots@mozilla.org in app-system-defaults
1510691213769	addons.xpi	DEBUG	Existing add-on followonsearch@mozilla.com in app-system-defaults
1510691213769	addons.xpi	DEBUG	Existing add-on formautofill@mozilla.org in app-system-defaults
1510691213770	addons.xpi	DEBUG	Existing add-on shield-recipe-client@mozilla.org in app-system-defaults
1510691213770	addons.xpi	DEBUG	Existing add-on aushelper@mozilla.org in app-system-defaults
1510691213770	addons.xpi	DEBUG	Existing add-on webcompat@mozilla.org in app-system-defaults
1510691213770	addons.xpi	DEBUG	Existing add-on e10srollout@mozilla.org in app-system-defaults
1510691213771	addons.xpi	DEBUG	Existing add-on onboarding@mozilla.org in app-system-defaults
1510691213771	addons.xpi	INFO	Mapping langpack-en-ZA@firefox.mozilla.org to /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1510691213771	addons.xpi	INFO	Mapping langpack-en-GB@firefox.mozilla.org to /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1510691213771	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1510691213771	addons.xpi	DEBUG	Existing add-on langpack-en-ZA@firefox.mozilla.org in app-global
1510691213771	addons.xpi	DEBUG	Existing add-on langpack-en-GB@firefox.mozilla.org in app-global
1510691213771	addons.xpi	DEBUG	Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1510691213772	addons.xpi	INFO	Mapping ubufox@ubuntu.com to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi
1510691213772	addons.xpi	DEBUG	Existing add-on ubufox@ubuntu.com in app-system-share
1510691213772	addons.xpi	DEBUG	getInstallState changed: false, state: {}
1510691214517	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/56.0/20171003222101/Linux_x86_64-gcc3/null/release-cck- ubuntu/Linux%204.13.0-16-generic%20(GTK%203.22.24%2Clibpulse%2010.0.0)/canonical/1.0/update.xml
1510691214819	addons.productaddons	INFO	Completed downloading document
1510691215341	addons.productaddons	INFO	downloadXHR File download. status=200
1510691215343	addons.productaddons	INFO	Downloaded file will be saved to /tmp/tmpaddon
1510691218434	DeferredSave.webext.sc.lz4	DEBUG	Starting write
1510691218435	DeferredSave.webext.sc.lz4	DEBUG	Write succeeded

firefox
    at new RuntimeError (/home/tturner/dev/WebdriverIO_Typescript/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/home/tturner/dev/WebdriverIO_Typescript/node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (/home/tturner/dev/WebdriverIO_Typescript/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/tturner/dev/WebdriverIO_Typescript/node_modules/webdriverio/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/tturner/dev/WebdriverIO_Typescript/node_modules/webdriverio/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

I'm new to node and wdio and trying to make sure I can test in both browsers before building out my test suite. The above seems to be the case both in my local Windows 10 x64 installation as well as in an Ubuntu 17.10 VM. When set to 'chrome', the tests execute without issue. I tried rolling back to previous versions of Firefox (54 and 56) but the result is the same. Any ideas?

**Comment by treyturner** [comment]
I drafted my own page object setup that seems to be working now, and can't really prove the issue wasn't my own, so I'm going to close.
